server:
  port: 8081
spring:
  application:
    name: greeting-service
greeting-service:
  greeting: "Hello"
  default-value: "World"
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
