server:
  port: 8081
spring:
  application:
    name: greeting-service
greeting-service:
  greeting: "Hola"
  default-value: "Mundo"
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
